Fix/27030
saucal/woocommerce-contribution pull request #2
Opened 2023-04-19 15:12 UTC by dpanta94

### Submission Review Guidelines:

- I have followed the [WooCommerce Contributing Guidelines](https://github.com/woocommerce/woocommerce/blob/trunk/.github/CONTRIBUTING.md) and the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- I have checked to ensure there aren't other open [Pull Requests](https://github.com/woocommerce/woocommerce/pulls) for the same update/change.
- I have reviewed my code for [security best practices](https://developer.wordpress.org/apis/security/). 
- Following the above guidelines will result in quick merges and clear and detailed feedback when appropriate.

### Changes proposed in this Pull Request:

Closes #27030 .

### How to test the changes in this Pull Request:

Using the [WooCommerce Testing Instructions Guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions), include your detailed testing instructions:

1. Create 2 Shipping Classes and 2 Shipping Zones (with Flat Rate added to each, we could name them New York and Florida).
2. Use the "Per Class" calculation type and only set rates for 1 class in each zone.
3. Create 2 products one adding the New York shipping class and the Florida to the other one
4. Add them to the cart individually, you should be able to complete your checkout if your shipping address matches the product's shipping class.
5. Add them to the cart together, you should never be able to complete your checkout. You should see that there are no shipping options available.

2023-04-19 15:29 UTC, alexiglesias31 reviewed
This looks good and works.
But perhaps an approach using `find_shipping_classes` and an operation with array_diff or something like that may be more suitable and intuitive here. However, that's only a thought after a quick checking. If not possible then this LGTM!

2023-04-19 17:19 UTC, msaggiorato requested changes

2023-04-19 17:19 UTC, msaggiorato commented on plugins/woocommerce/includes/class-wc-shipping.php
> +			if ( apply_filters( 'woocommerce_skip_shipping_rates_validation', false, $package, $package_key, $this->packages ) ) {
Maybe it should be agreed upon with Woo if we should set the default to true or false here?

2023-04-19 17:19 UTC, msaggiorato commented on plugins/woocommerce/includes/class-wc-shipping.php
> +
It'd be good to add a test case as well which reproduces the problem so that this fix shows the problem as fixed.

2023-04-19 17:23 UTC, dpanta94 commented on plugins/woocommerce/includes/class-wc-shipping.php
> +			if ( apply_filters( 'woocommerce_skip_shipping_rates_validation', false, $package, $package_key, $this->packages ) ) {
I guess they will have the oppurtinity to review it themselves so they could decide

2023-07-11 10:32 UTC, dpanta94 commented
Merged in Woo repo! 🚀

2023-07-11 10:32 UTC, closed without merging